version: '3.8'
services:
  backend:
    build: ./backend
    container_name: xiseed-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/xiseed
    depends_on:
      - db
    networks:
      - xiseed-net
  frontend:
    build: ./frontend
    container_name: xiseed-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - xiseed-net
  db:
    image: postgres:15-alpine
    container_name: xiseed-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: xiseed
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - xiseed-net
  redis:
    image: redis:7-alpine
    container_name: xiseed-redis
    restart: always
    networks:
      - xiseed-net
volumes:
  pgdata:
networks:
  xiseed-net:
    driver: bridge 